git-ftp, tests/git-ftp-test.sh
It's a bloody big change, but I think it's the right way to go.
The patterns in .git-ftp-ignore where applied to the output of `git diff` or `git ls-files -t`:
M modifield_file.txt
D deleted_file.txt
You had to consider that to ignore a single file (issue #80).
Now that output is split into a list of files to upload and another list
of files to delete. These lists can be filtered properly.
It also simplifies adding files from the include-file and handling the file sync.
=> Supporting regex for ignore file

git-ftp
The only way to give curl a username that contains a colon (:) is to encode it in the URL (http://curl.haxx.se/mail/archive-2009-12/0009.html). These commits add url-encoding of username and password and put these into the remote url instead of giving `--user <user:password>`.
=> Using colon in username

git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
Using a POSIX shell statement to filter file lists. This implementation
is probably a lot slower than the previous `grep` calls and could be
optimised.
This should solve #80.
=> Filtering with shell glob patterns instead of regex

git-ftp, man/git-ftp.1.md
git-ftp now tries to read the `git config git-ftp.keychain` entry and use it to retrieve username and password for the FTP server
=> Added ability to set a default keychain entry via git config

git-ftp, tests/git-ftp-test.sh
The command `mktemp` is not available in the current Git for Windows
release (#172). If mktemp cannot be found, this version will use
.git/git-ftp-tmp as temporary directory. The creation of the temporary
directory is also delayed until it's needed by set_changed_files and
handle_file_sync (actions init and push only).
=> Failsafe mktemp

git-ftp, tests/git-ftp-test.sh
Adresses issue #169.
I'm not sure if the test for a slash as last character works in all shells:
```
if [ "${TARGET: -1}" != '/' ]; then
...
fi
```
=> Delete files in .git-ftp-include only if locally deleted

INSTALL.md
A note about how to make git-ftp work on Windows with both msysgit and cygwin installed and added in PATH.
=> Description for Windows with both msysgit and cygwin installed

Makefile, man/Makefile
Also:
- ~~change the default mandir to $(prefix)/share/man/man1~~
- allow `make install-man` to succeed on systems without mandb (such as Mac OS X)
=> Makefiles: allow custom bindir and mandir

.travis.yml
This will allow vsftpd to be installed via apt-get on Travis CI.
=> Add `sudo apt-get update` in .travis.yml

git-ftp
With git v2.7.x, running `git submodule status -- "$syncroot"` on a repository
print the error message "error: pathspec '' did not match any file(s) known to
git." in stderr.
This commit redirect the stderr output to /dev/null to hide the error message
from console output.
=> Suppress submodule status error message of git v2.7

git-ftp, tests/git-ftp-test.sh
Includes a list of modified files in the commit message after the pull.
The verbose commit message contains the output of `git diff HEAD --name-status`:
```
[git-ftp] remotely untracked modifications
A	uploads/new_image.jpg
D	data/removed_file.dat
M	pages/modified_content.txt
```
My personal use case is an FTP-hosted website running on [Grav](http://getgrav.org/) with user-generated content stored as plaintext Markdown files that I keep track of with a daily cronjob à la `git ftp pull && git push`. With verbose commit messages I can see the changes at a glance in my Gitlab repository overview and don't have to manually open each commit to see what files (=pages) have been changed.
=> New option --verbose-commit

git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
Hi.
Here is a pull request concerning this idea https://github.com/git-ftp/git-ftp/issues/279
I made it the default behavior of the pull command; old behavior is achieved by adding the --all parameter
So, basically, instead of checking all the files on the FTP server it checks just for the modified files.
Modified files are determined by a git diff beetween the FTP commit and the current branch/commit.
We could handle things differently, I just quickly put it this way because I needed it asap.
I took some extra time to edit the tests and docs.
=> Pull action only checking files based on diff

man/git-ftp.1.md
Fix https://github.com/git-ftp/git-ftp/issues/348.
The documentation stated that the syncroot can be used with all paths in .git-ftp-ignore. That is not true. The syncroot is only applied to Git tracked source files on the right side of the colon.
@JoshuaCrewe Can you confirm that the updated description is not confusing and is correct?
=> Correct description of .git-ftp-include with syncroot

git-ftp, tests/git-ftp-test.sh
During the push action, when the remote commit is unknown, Git-ftp asks
if it should just upload all files again. If the user doesn't give an
answer, the script now exits with code 2 "usage error".
This happens in automated deploy scripts which should fail in this case.
See: #334
=>  Fail if remote commit is unknown and no input

git-ftp
Otherwise the last exclude item generated from .git-ftp-ignore
merges with --exclude=^\.git/, invalidating both.
=> Separate lftp excludes properly (fixes #377)

git-ftp
Since git 2.11.0 the ls-files subcommand behaves like:
$ git ls-files -- ""
warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
[...]
We'd better follow the advice.
=> Avoid git warning: empty strings as pathspecs

AUTHORS, man/git-ftp.1.md
Continuation of #163, which only documented the command-line option.
In the general `git config git-ftp` line, added ellipse as not all configs were already included.
=> Add config git-ftp.remote-root to docs

git-ftp, tests/git-ftp-test.sh
post-ftp-push is not getting the correct $DEPLOYED_SHA1 because it's overriten in the previous steps. 
This is an attempt to fix this
=> Fixed post hook reference to deployed SHA1

git-ftp
* Ensure `curl` command is availiable on the hosts and print a "user friendly" error message
* Ensure the `$REMOTE_PROTOCOL` is supported by the host's `curl` and print a "user friendly" error message : some linux distro (eg. Ubuntu) ship a `curl` version that does not support `sftp`
=> add a check covering curl presence and protocol support

INSTALL.md
Current installation instructions will not work on OS X without first running ```brew install brotli```. 
Users will experience the following without that command:
```dyld: Library not loaded: /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
Referenced from: /usr/local/Cellar/git-ftp/1.4.0_5/libexec/bin/curl
Reason: image not found
```
In addition, when running ``` brew install curl --with-ssl --with-libssh2```, users will get the following:
```
Warning: curl: this formula has no --with-ssl option so it will be ignored!
```
So it's removed from the file.
=> Update INSTALL.md instructions for OS X 10.13.3

git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
By default, `post-ftp-push` hook errors doesn't triggers a `git ftp` error.
This makes scripting painful as hook errors are not detectable.
(eg. when one want's to prune the host's cache and when a locked file leads to a hook failure and the CI job ends in success ...)
Hence this new option `--enable-post-errors` which allows error propagation
=> Adds an option which allow a post-ftp-push script error to be fatal

git-ftp
the last line of .git-ftp-ignore as ecclude and var ignore in function download_remote_updates get attached to closely, so that something like --exclude XYZ--exclude ^.git/ happens. The last line and the first ignore statement thereby don't work. Inserting a space at the beginning of the ignore variable solves this problem.
=> insert space to not mess up lftp exclude options

git-ftp, tests/git-ftp-test.sh
Fixes #448.
A check for supported protocols by curl (8bb8f7ccad3b7c1f6cecb6a5ce6367fb05c3cbab) didn't handle FTPES properly.
=> Fix check for FTPES protocol support

INSTALL.md
The installation instructions were slightly off for the later versions of Git for Windows. Made some slight corrections.
=> Updated INSTALL.md with clearer and more up-to-date instructions for Windows

git-ftp
If SFTP is used, the curl parameter `--ftp-create-dirs` has no effect. This means the directory is not created if it does not exist.
Therefore we have to check if we use SFTP and if the access check returns `78` (No such file or directory), we try to send a create command for the directory.
fixes #311
fixes #496
This could also be part of the solution for #295, since it allows to create the directory for submodules during submodule handling.
**Limitations**
According to the [specification of SFTP](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-00#section-6.6) there is no option to create directories recursively. This means that the parent folder of syncroot must exist. Otherwise the create request will fail.
*Example:* If the syncroot is set to `/var/htdocs/html/project/` the …
=> fix: directory creation with SFTP

git-ftp
The check if a file/directory is a submodule was broken. A detailed analysis to this issue can be found [here](https://github.com/git-ftp/git-ftp/issues/295#issuecomment-488627926) in #295.
This fixes this issue by setting `SYNCROOT` earlier in the call stack, so `cache_git_submodules` will work as expected.
fixes #295
**Limitations**
To the current state, handling of submodules only works with username and password. Usage of ssh-keys with submodules does not work. (see #507)
=> fix: submodule handling

tests/git-ftp-test.sh
As described in #509 `tearDown()` was not deleting any test projects from the test ftp server.
This fixes this issue by using the parent directory url for this call.
fixes #509
=> fix: Deleting of test data

CHANGELOG.md, git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
Pull request #504 introduced new logic to create directories with sftp.
As mentioned in the [discussion to this](https://github.com/git-ftp/git-ftp/pull/504#discussion_r281009161) the error handling is not perfect. This commit fixes this issue.
At first do the curl request as before bot cache the exit code in a local variable.
The we can check if sftp was used and `$EXIT_CODE` was `78`. If so do the creation stuff. If not check the $EXIT_CODE for other errors.
=> fix: error handling with new sftp directory creation

.travis.yml
As discussed in #513 this implements a installing mechanism for lftp in Travis CI.
It uses the build matrix feature to install lftp addon on both platforms. So the installation can be removed from the install part of the script.
fixes #513
=> Travis lftp

CHANGELOG.md, git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
This pull request adds the option to configure a default value for `disable-epsv` using `git config`.
As well it adds support for `true` and `false` for boolean options, so you can use now:
```sh
$ git config git-ftp.insecure true
$ git config git-ftp.disable-epsv true
```
And some tests for this new features are added.
=> Enhancement epsv option

CHANGELOG.md, git-ftp, tests/git-ftp-test.sh
Allows `/` in scopes names. This is required to enable auto detection for nested branches. (see #511) 
As well more helpful error messages are added if an invalid scope name is used.
=> Enhancement scope names

CHANGELOG.md, git-ftp, tests/git-ftp-test.sh
Add support for `--insecure` and FTPS when using LFTP (download and pull).
I did some refactoring in `download_remote_updates()` to make it more readable and make the mechanism similar to the one used for curl. This way it’s easier to maintain.
=> LFTP options

CHANGELOG.md, git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
This introduces a mechanism to check curl commands for exit code `67` to catch authentication problems and displaying a proper error message in such cases.
In addition some test are adjusted and added to cover the new behaviour.
And then some documentation for password specific issues is added, in particular for passwords with special characters and the OSX keychain.
=> Passwords: Error detection and documentation

tests/git-ftp-test.sh
With this pull request the legacy `cd` commands are removed since this is done in `set_up` now and the new error code constants are used in asserts instead of fixed integers.
=> Better tests

CHANGELOG.md, git-ftp, man/git-ftp.1.md, tests/git-ftp-test.sh
- Changes processing of boolean configs by handling them as integers instead of strings.
- Forces non-fast-forward merges if `--no-commit` is set for pull action (see #528)
- Adds default processing for `no-commit`
- Adds some detail to documentation
=> Pull no commit

INSTALL.md
Adds easier installation instructions as an alternative for installation with Git.
resolves #355
=> Doc: Add installation instructions for direct download

.github/stale.yml
I misunderstood the config for stale-bot sorry.
I thought of the onlyLabels as "one of these labels" has to be set, but in fact it is "ALL of these labels has to be set". And obviously we don’t have a single issue that has all these four labels (needs_info, question, ci, duplicate). So the bot might work but is not finding any issue to close.
So we had to change the label strategy for the bot and came up with this solution.
=> Fix stale-bot onlyLabels

AUTHORS, README.md
I wrote [this github action](https://github.com/SamKirkland/FTP-Deploy-Action) that allows you to automatically deploy code via github actions. This is just a wrapper around git-ftp 😄
=> Adding link to git-ftp github action

git-ftp, tests/git-ftp-test.sh
Fixes #633 
Fixes an issue with recent versions of Curl not handling correctly space characters in URLs
Curl now seems to not accept URLs with spaces : https://github.com/curl/curl/issues/8654
To fix this issue, space characters are replaced by %20
=> Fix issue with Curl and space characters in filename

git-ftp, man/git-ftp.1.md
Add option to bypass post hooks just like the --no-verify option allows to bypass pre hooks which I needed for a specific use case. EXECUTE_HOOKS could be renamed to EXECUTE_PRE_HOOKS for specificity, but I didn't want to break any code that could use it unbeknownst to me.
=> Adding --no-post-hooks to bypass post hooks.
