git-ftp/git-ftp

man/git-ftp.1.md

There is no specification about --remote-root, so add to man file

Add --remote-root to man file

---

man/git-ftp.1.md

Remove a redundant sentence from the man page (the man page is about git-ftp? who would have guessed... ;-), and fix a few spelling mistakes.

Some minor cleanup

---

AUTHORS
git-ftp
man/git-ftp.1.md

Add possibility to push a specific git branch
------------------------------------------------------
Use ```-b [branch]``` or ```--branch [branch]``` to specify the branch to push.
Git ftp will checkout to this branch, do his stuff and checkout again to the current working branch.

Add possibility to push specific branch

---

git-ftp
tests/git-ftp-test.sh

Calling catchup on submodules. Addressing issue #37.

Submodule catchup #37

---

git-ftp

Changed main script to show ```file``` or ```files``` based on the number of buffered uploads.

To ease all of our programming induced OCD

---

git-ftp
tests/git-ftp-test.sh

Ignore uninitialised submodules

---

git-ftp

correct parsing of :// in add-scope

---

tests/git-ftp-test.sh

Don't change directory for testing

---

git-ftp

Add X's to satisfy the busybox version of mktemp
Fixes #323

Update mktemp Pattern

---

git-ftp
man/git-ftp.1.md
tests/git-ftp-test.sh

Merge request for #290 
Usage: 
`git ftp push --auto-init`

Add --auto-init for push action

---

git-ftp
tests/git-ftp-test.sh

Following https://github.com/git-ftp/git-ftp/pull/341.
Addressing #319 and #320.
@adrum I tried to combine my previous work with yours. What to you think about this solution? Does it contain everything you would like?

Separate key options

---

git-ftp
man/git-ftp.1.md
tests/git-ftp-test.sh

Test and document patterns to ignore Git files

---

git-ftp
man/git-ftp.1.md

Introducing the EXAMPLES section in the manual.
See: https://github.com/git-ftp/git-ftp/issues/357

Document using SFTP

---

README.md
man/git-ftp.1.md

Extending the documentation to avoid issues like https://github.com/git-ftp/git-ftp/issues/288.

Ftp doc issues

---

INSTALL.md

Changed the classic Mac OS X wording to MacOS.

Extremely basic word changes

---

man/git-ftp.1.md

Suggestion based on my test, see #393

Add suggestion for usage with GIT LFS

---

CHANGELOG.md
git-ftp
tests/git-ftp-test.sh

I found a bug where the `insecure` option is not read from config.
And I fixed it.

Enable loading of `insecure` option from config

---

git-ftp

If core.hooksPath is set we should use it
Should be solve #498

Use core.hooksPath configuration

---

CHANGELOG.md
git-ftp
tests/git-ftp-test.sh

This pull request adds two enhancements for submodule handling. 
* Pass insecure flag to submodule if set. Thanks to @madaxel on this. https://github.com/git-ftp/git-ftp/issues/471#issuecomment-436229263
* Add support for key authentication with submodules when using ssh #507 
More details can be found in the related issues and commit messages.
closes #471 
closes #507

Enhancement submodules

---

INSTALL.md
README.md
man/git-ftp.1.md

This pull request adds some more detail to the documentation. It addresses 3 topics
- A more detailed description for .netrc (see #453)
- A detailed guide for SFTP on macOS (see #503)
- Links to changelog (see #517)

Enhancements for documentation

---

tests/git-ftp-test.sh

Fixed typo: GitHub case

---

.github/stale.yml

Remove the evil space to make stale-bot finally work.

Fix stale-bot config
